### ISSUE TITLE
build fails on folders containing special character

### ISSUE THREAD

**Issue by mihaly-pajerich** [everit-org/eosgi-maven-plugin#24]
Build fails on special caharcters:

"#test"
[ERROR] Failed to execute goal org.everit.osgi.dev:eosgi-maven-plugin:3.2.0:integration-test (integration-test) on project xxxx.yyy: Failed to process already existing distribution configuration file: D:\dev#test\xxxx\tests\target\eosgi-dist\equinoxtest.eosgi.dist.xml -> [Help 1]

**Comment by balazs-zsoldos** [comment]
Fixed in 4.0.4
